import { CustomerJob, Quote, PricingItem, ContentIdea } from "./types";
import { generateId } from "./utils";

export function getSeedJobs(): CustomerJob[] {
  const now = new Date();
  return [
    {
      id: generateId(),
      customerName: "Erik Lindström",
      phone: "070-123 45 67",
      email: "erik@example.com",
      vehicleType: "Elsparkcykel",
      brandModel: "Xiaomi Pro 2",
      problem: "Bromsar sliter och gnisslar vid låg hastighet",
      internalNotes: "Troligen bromsbelägg, kolla kabel också",
      status: "Pågår",
      price: 850,
      paymentStatus: "Ej betald",
      source: "Website",
      nextStep: "Byt bromsbelägg",
      createdAt: new Date(now.getTime() - 2 * 86400000).toISOString(),
      preferredDate: new Date(now.getTime() + 86400000).toISOString(),
      pickupDelivery: "Kunden lämnar",
      campaignCode: "",
    },
    {
      id: generateId(),
      customerName: "Anna Svensson",
      phone: "073-987 65 43",
      email: "anna.s@example.com",
      vehicleType: "Elcykel",
      brandModel: "Batavus Finez E-go",
      problem: "Batteri laddar inte fullt, stannar vid 80%",
      internalNotes: "BMS-fel? Kolla cellbalans",
      status: "Felsökning",
      price: 0,
      paymentStatus: "Ej betald",
      source: "Phone",
      nextStep: "Diagnostisera batteri",
      createdAt: new Date(now.getTime() - 86400000).toISOString(),
      preferredDate: "",
      pickupDelivery: "Hämtning",
      campaignCode: "",
    },
    {
      id: generateId(),
      customerName: "Mohammed Al-Rashid",
      phone: "076-555 12 34",
      email: "mo.rashid@example.com",
      vehicleType: "Elsparkcykel",
      brandModel: "Segway Ninebot Max G30",
      problem: "Punktering bakhjul",
      internalNotes: "",
      status: "Klar",
      price: 650,
      paymentStatus: "Väntar på betalning" as CustomerJob["paymentStatus"],
      source: "Walk-in",
      nextStep: "Kontakta kund för hämtning",
      createdAt: new Date(now.getTime() - 3 * 86400000).toISOString(),
      preferredDate: "",
      pickupDelivery: "Kunden hämtar",
      campaignCode: "",
    },
    {
      id: generateId(),
      customerName: "Lisa Bergqvist",
      phone: "070-222 33 44",
      email: "lisa.b@example.com",
      vehicleType: "Elcykel",
      brandModel: "Crescent Elora",
      problem: "Display visar felkod E08, motorn startar inte",
      internalNotes: "Beställ ny controller om det behövs",
      status: "Väntar på delar",
      price: 2200,
      paymentStatus: "Delbetald",
      source: "Referral",
      nextStep: "Väntar på controller från leverantör",
      createdAt: new Date(now.getTime() - 5 * 86400000).toISOString(),
      preferredDate: new Date(now.getTime() + 3 * 86400000).toISOString(),
      pickupDelivery: "Hämtning/Lämning",
      campaignCode: "VÄNNER10",
    },
    {
      id: generateId(),
      customerName: "Karl Johansson",
      phone: "072-111 22 33",
      email: "",
      vehicleType: "Elsparkcykel",
      brandModel: "Xiaomi 1S",
      problem: "Fullständig service och rengöring",
      internalNotes: "",
      status: "Ny",
      price: 499,
      paymentStatus: "Ej betald",
      source: "Instagram",
      nextStep: "Bekräfta bokning",
      createdAt: new Date().toISOString(),
      preferredDate: new Date(now.getTime() + 2 * 86400000).toISOString(),
      pickupDelivery: "Kunden lämnar",
      campaignCode: "INSTA20",
    },
    {
      id: generateId(),
      customerName: "Sara Ekström",
      phone: "070-444 55 66",
      email: "sara.e@example.com",
      vehicleType: "Elcykel",
      brandModel: "Specialized Turbo Vado",
      problem: "Kedja hoppar vid hög belastning",
      internalNotes: "Klar. Bytte kedja och kassett.",
      status: "Slutförd",
      price: 1450,
      paymentStatus: "Betald",
      source: "Website",
      nextStep: "",
      createdAt: new Date(now.getTime() - 7 * 86400000).toISOString(),
      preferredDate: "",
      pickupDelivery: "Kunden lämnar",
      campaignCode: "",
    },
  ];
}

export function getSeedPricing(): PricingItem[] {
  return [
    { id: generateId(), service: "Grundläggande felsökning", category: "Felsökning", standardPrice: 495, minPrice: 395, premiumPrice: 695, note: "Upp till 30 min" },
    { id: generateId(), service: "Avancerad felsökning", category: "Avancerad felsökning", standardPrice: 895, minPrice: 695, premiumPrice: 1295, note: "Elektronik, BMS, firmware" },
    { id: generateId(), service: "Standardservice", category: "Service", standardPrice: 499, minPrice: 399, premiumPrice: 699, note: "Bromsar, däck, kedja, rengöring" },
    { id: generateId(), service: "Punktering framhjul", category: "Punktering", standardPrice: 450, minPrice: 350, premiumPrice: 550, note: "" },
    { id: generateId(), service: "Punktering bakhjul", category: "Punktering", standardPrice: 550, minPrice: 450, premiumPrice: 650, note: "Bakhjul tar längre tid" },
    { id: generateId(), service: "Bromsjustering", category: "Bromsar", standardPrice: 295, minPrice: 195, premiumPrice: 395, note: "Per broms" },
    { id: generateId(), service: "Byte bromsbelägg", category: "Bromsar", standardPrice: 495, minPrice: 395, premiumPrice: 595, note: "Inkl. delar" },
    { id: generateId(), service: "Batteritest & diagnostik", category: "Batteri", standardPrice: 595, minPrice: 495, premiumPrice: 795, note: "Cellbalanstest inkluderat" },
    { id: generateId(), service: "Kabeldragning", category: "Kabeldragning", standardPrice: 395, minPrice: 295, premiumPrice: 595, note: "Per timme" },
    { id: generateId(), service: "Hämtning/Lämning", category: "Hämtning/Lämning", standardPrice: 299, minPrice: 199, premiumPrice: 499, note: "Inom 10 km" },
  ];
}

export function getSeedContentIdeas(): ContentIdea[] {
  return [
    {
      id: generateId(),
      title: "Xiaomi Pro 2 bromsfix – före/efter",
      type: "Före/Efter",
      notes: "Filma bromsljudet före, sen tyst efter fix",
      status: "Idé",
      hook: "Hör du det här ljudet från din elsparkcykel? 🔊",
      problem: "Gnisslande bromsar som många Xiaomi-ägare känner igen",
      solution: "Vi bytte bromsbelägg och justerade vajern",
      result: "Tysta, säkra bromsar igen – på under 30 minuter",
      cta: "Boka din bromsservice idag – länk i bio",
      createdAt: new Date().toISOString(),
    },
    {
      id: generateId(),
      title: "Batterilivslängd – 5 tips",
      type: "Servicetips",
      notes: "Kort reel med text-overlay",
      status: "Utkast",
      hook: "",
      problem: "",
      solution: "",
      result: "",
      cta: "",
      createdAt: new Date().toISOString(),
    },
  ];
}
